/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "fit5225a2api",
            "endpoint": "https://s0uosv2h3l.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:7a555bad-9c24-4d20-8103-a11091ad6ef6",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_EaAdnqVZ6",
    "aws_user_pools_web_client_id": "3iu4mre1cqlatdik48qv4ipjj4",
    "oauth": {},
    "aws_user_files_s3_bucket": "fit5225assignment2s3",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "fit5225assignment2db",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
